source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'FSQCollectionViewAlignedLayout', :git => "https://github.com/tomaskraina/FSQCollectionViewAlignedLayout.git"

target 'BubbleTagView_Example', :exclusive => true do
  pod "BubbleTagView", :path => "../"
end

target 'BubbleTagView_Tests', :exclusive => true do
  pod "BubbleTagView", :path => "../"

  
end
